export const greekPrepositions = {
  Διὰ: "through/because of",
  Εἰς: "unto/toward",
  Κατʼ: "according to",
  Κατὰ: "according to",
  Μεθʼ: "with/after",
  Μετὰ: "with/after",
  Παρὰ: "from/with/beside",
  Περὶ: "about/concerning",
  Πρὸ: "before",
  Πρὸς: "to/with",
  απο: "away from",
  διʼ: "through/because of",
  διά: "through/because of",
  διὰ: "through/because of",
  εἰς: "unto/toward",
  εἴς: "unto/toward",
  εἵνεκεν: "because of",
  καθʼ: "according to",
  κατ: "according to",
  κατʼ: "according to",
  κατά: "according to",
  κατέναντι: "before",
  κατενώπιον: "before",
  κατὰ: "according to",
  μέχρι: "until",
  μέχρις: "until",
  μεθʼ: "with/after",
  "μεθ᾿": "with/after",
  μετʼ: "with/after",
  μεταξὺ: "between/meanwhile",
  μετὰ: "with/after",
  πέραν: "other side",
  παρʼ: "from/with/beside",
  παρ: "from/with/beside",
  παρά: "from/with/beside",
  παρεκτὸς: "except",
  παρὰ: "from/with/beside",
  περί: "about/concerning",
  περὶ: "about/concerning",
  πλὴν: "but/however",
  πρός: "to/with",
  πρὸ: "before",
  πρὸς: "to/with",
  σύν: "with",
  σὺν: "with",
  χωρίς: "without",
  χωρὶς: "without",
  ἀνθʼ: "for",
  ἀντὶ: "for",
  ἀνὰ: "each",
  ἀπʼ: "away from",
  ἀπέναντι: "opposite",
  ἀπό: "away from",
  ἀπὸ: "away from",
  ἀφʼ: "away from",
  ἄνευ: "without",
  ἄτερ: "without",
  ἄχρι: "until",
  ἄχρις: "until",
  Ἀπὸ: "away from",
  Ἄχρι: "until",
  ἐγγύς: "near",
  ἐγγὺς: "near",
  ἐκ: "out from",
  ἐκτὸς: "outside/except",
  ἐν: "in/on/among",
  ἐνώπιον: "before",
  ἐνώπιόν: "before",
  ἐξ: "out from",
  ἐπʼ: "upon/to/against",
  ἐπάνω: "above",
  ἐπέκεινα: "beyond",
  ἐπί: "upon/to/against",
  ἐπὶ: "upon/to/against",
  ἐφʼ: "upon/to/against",
  ἔμπροσθέν: "before",
  ἔμπροσθεν: "before",
  ἔν: "in/on/among",
  ἔναντι: "before",
  ἔξω: "out/outside(r)",
  ἕνεκα: "because of",
  ἕνεκεν: "because of",
  ἕως: "until",
  Ἐγγύς: "near",
  Ἐκ: "out from",
  Ἐν: "in/on/among",
  Ἐξ: "out from",
  Ἐπʼ: "upon/to/against",
  Ἐπὶ: "upon/to/against",
  Ἐφʼ: "upon/to/against",
  Ἕνεκα: "because of",
  Ἕνεκεν: "because of",
  Ἕως: "until",
  ὀπίσω: "after",
  Ὀπίσω: "after",
  ὑπʼ: "under/awayby",
  ὑπεράνω: "above",
  ὑπερέκεινα: "beyond",
  ὑποκάτω: "under",
  ὑπό: "under/by",
  ὑπὲρ: "above/for",
  ὑπὸ: "under/by",
  ὑφʼ: "under",
};
