export const greekConjunctions = {
  Διό: "therefore",
  Διόπερ: "for",
  Διότι: "because",
  Διὸ: "therefore",
  Εἴτε: "whether",
  Καί: "and/also",
  Καθάπερ: "just as",
  Καθὼς: "as/just as",
  Καὶ: "and/also",
  Μήποτε: "lest",
  Οὐδὲ: "and not",
  Οὐκοῦν: "so",
  Οὔτε: "neither",
  Τοίνυν: "then",
  Τοιγαροῦν: "therefore",
  γάρ: "for",
  γὰρ: "for",
  δʼ: "but/and/then",
  δέ: "but/and/then",
  διό: "therefore",
  διόπερ: "for",
  διότι: "because",
  διὸ: "therefore",
  δὲ: "but/and/then",
  εἴπερ: "if so/since",
  εἴτε: "whether...or",
  καί: "and",
  καίπερ: "although",
  καίτοι: "and yet/although",
  καίτοιγε: "and yet/although",
  καθάπερ: "just as",
  καθότι: "as/just as",
  καθώς: "as/just as",
  καθώσπερ: "as",
  καθὰ: "as/just as",
  καθὸ: "insofar as",
  καθὼς: "as/just as",
  καὶ: "and",
  κἂν: "and/even if",
  μέντοι: "yet",
  "μή πως": "so that",
  μήποτέ: "lest",
  μήτε: "neither",
  μηδʼ: "nor",
  μηδὲ: "nor",
  οὐδʼ: "and not",
  οὐδέ: "and not",
  οὐδὲ: "and not",
  οὔτε: "neither",
  οὖν: "therefore/then",
  πρὶν: "before",
  τε: "and/both",
  τοίνυν: "then",
  τοιγαροῦν: "therefore",
  ἀλλʼ: "but",
  ἀλλά: "but",
  ἀλλὰ: "but",
  "ἀλλ᾿": "but",
  ἄρα: "therefore",
  ἆρα: "no?",
  Ἀλλʼ: "but",
  Ἀλλὰ: "but",
  "Ἀλλ᾿": "but",
  Ἄρα: "therefore",
  Ἆρά: "no?",
  ἐάνπερ: "if indeed",
  ἐπειδὴ: "since",
  ἐπεὶ: "since",
  ἐπὰν: "when/as soon as",
  Ἐάν: "if",
  Ἐπειδήπερ: "since",
  Ἐπειδὴ: "since",
  Ἐπεὶ: "since",
  Ἐὰν: "if",
  ἡνίκα: "when",
  ἢ: "or",
  ἤ: "or",
  ἤπερ: "than",
  ἤτοι: "whether",
  Ἢ: "or",
  ἵνα: "in order that/to",
  Ἵνα: "in order that/to",
  ὁσάκις: "whenever",
  ὅθεν: "whence",
  ὅπου: "where(-ever)",
  ὅπως: "that",
  ὅταν: "when(-ever)",
  ὅτε: "when",
  ὅτι: "that/becaus/since",
  Ὅθεν: "whence",
  Ὅπου: "where(-ever)",
  Ὅπως: "that",
  Ὅταν: "when(-ever)",
  Ὅτε: "when",
  Ὅτι: "that/because/since",
  ὡς: "as/when",
  ὡσεὶ: "like/as/about",
  ὡσπερεὶ: "just as if",
  ὥς: "as/when",
  ὥσπερ: "just as",
  ὥστε: "so",
  Ὡς: "as/when",
  Ὥσπερ: "just as",
  Ὥστε: "so",
};
